---
  - name: USE | Detect upstart system
    shell: |
      if [[ `/sbin/init --version 2> /dev/null` =~ upstart ]]; then echo upstart;
      elif [[ `systemctl` =~ -\.mount ]]; then echo systemd;
      elif [[ -f /etc/init.d/cron && ! -h /etc/init.d/cron ]]; then echo sysv-init;
      else echo UNKNOWN;
      fi
    become: yes
    changed_when: false
    args:
      executable: /bin/bash
    register: upstart_detect_raw

  - name: set upstart_system fact
    set_fact:
      upstart_system: "{{ upstart_detect_raw.stdout }}"
