---

  - set_fact:
      npm_source_path: ""

  - name: Node Location | Check if user .profile present on usual location
    command: test -e /home/{{deploy_user}}/.profile
    ignore_errors: yes
    become: "{{deploy_user}}"
    register: dot_profile_present_usual

  - set_fact:
      npm_source_path: "/home/{{deploy_user}}/.profile &&"
    when: not (dot_profile_present_usual | failed)

  - name: Node Location | Check if user .profile present on unusual location
    command: test -e /{{deploy_user}}/.profile
    when: dot_profile_present_usual | failed
    ignore_errors: yes
    become: "{{deploy_user}}"
    register: dot_profile_present_unusual

  - set_fact:
      npm_source_path: "/{{deploy_user}}/.profile &&"
    when: not(dot_profile_present_unusual | failed) and (dot_profile_present_usual | failed)

  - name: NODE LOCATION | Detect npm
    shell: '{{npm_source_path}} dirname "`which npm`"'
    args:
       executable: /bin/bash
    register: npm_path_detected_raw
    become: "{{deploy_user}}"

#  - debug: var="npm_path_detected_raw"

  - set_fact:
      npm_path_detected: "{{ npm_path_detected_raw.stdout }}"
      npm_is_global: "{{npm_path_detected_raw.stdout.find('.nvm') == -1}}"

  - debug: msg="{{ npm_path_detected_raw }} thus npm global is {{npm_is_global}}"

# Usage example:
#    - name: Install ember-cli
#    npm: name=ember-cli state=present version="{{node.ember.version}}" global=yes executable="{{npm_path_detected}}/npm"
#    become: "{{npm_is_global}}"
#    environment:
#      PATH: "{{npm_path_detected}}:{{ ansible_env.PATH }}"       # can be different depending on nvm version
#    tags:
#      - create
