---

  - name: Protractor | Install protractor
    npm: name=protractor state=present global=yes executable="{{npm_path_detected}}/npm"
    become: "{{npm_is_global}}"
    environment:
      PATH: "{{npm_path_detected}}:{{ ansible_env.PATH }}"
    tags:
      - protractor
