---

  - name: Protractor | Detect npm
    shell: 'source /home/{{deploy_user}}/.profile && dirname "`which npm`"'
    args:
       executable: /bin/bash
    register: npm_path_detected_raw
    become: "{{deploy_user}}"

  - set_fact:
      npm_path_detected: "{{ npm_path_detected_raw.stdout }}"
      npm_is_global: "{{npm_path_detected_raw.stdout.find('.nvm') == -1}}"

  - debug: msg="{{ npm_path_detected_raw }} thus npm global is {{npm_is_global}}"


  - name: Protractor | Install protractor
    npm: name=protractor state=present global=yes executable="{{npm_path_detected}}/npm"
    become: "{{npm_is_global}}"
    environment:
      PATH: "{{npm_path_detected}}:{{ ansible_env.PATH }}"
    tags:
      - protractor
