---
  - name: Browsers | Install packages required by browsers
    apt:
     pkg:
      - "x11-xkb-utils"
      - "xfonts-100dpi"
      - "xfonts-75dpi"
      - "xfonts-scalable"
      - "xserver-xorg-core"
      - "libfontconfig1-dev"
     state: present
    become: yes
    tags:
      - browsers

  - name: Browsers | Install firefox browser
    apt:
      pkg:
       - "firefox"
      state: present
    when: browser_firefox
    become: yes
    tags:
      - browsers

  - name: Browsers | Install chromium browser
    apt:
     pkg:
      - "chromium-browser"
     state: present
    when: browser_chromium
    become: yes
    tags:
      - browsers

  - name: Browsers | Install phantomjs
    npm: name=phantomjs state=present global=yes executable="{{ npm_path_detected }}/npm"
    when: browser_phantomjs
    become: "{{ npm_is_global }}"
    environment:
      PATH: "{{ npm_path_detected }}:{{ ansible_env.PATH }}"
    tags:
      - browsers

  - include: tasks_google_chrome.yml
    when: browser_google_chrome

  - name: Browsers | Install chromedriver
    npm: name=chromedriver state=present global=yes executable="{{ npm_path_detected }}/npm"
    become: "{{ npm_is_global }}"
    environment:
      PATH: "{{ npm_path_detected }}:{{ ansible_env.PATH }}"
    tags:
      - browsers
