---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-ci-e2e-headless",
         option_install_java: true
       }


  tasks:
    - debug: msg="Tasks section"
